---
title: "Manuscript 1 from Fernanda Hansen P. de Moraes Thesis - Cortical folding alterations in humans due to aging and diseases"
author: "Fernanda Hansen Pacheco de Moraes"
date: "1 dec 2021"
output:
  html_document: 
    fig_caption: yes
    fig_width: 8
    number_sections: yes
    theme: paper
    toc: yes
    toc_depth: 6
editor_options: 
  chunk_output_type: inline
---

# RMARKDOWN AND R SETUP
```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = TRUE,
	message = FALSE,
	warning = FALSE,
	cache = TRUE
)
```

```{r working directory}
setwd("D:/GitHub/CorticalFolding_AD_Aging")
```

```{r functions, message=FALSE, warning=FALSE}
## define functions

# test angular coeficinet versus theoretical value
test_coef <- function(reg, coefnum, val){
  co <- coef(summary(reg))
  tstat <- (co[coefnum,1] - val)/co[coefnum,2]
  2 * pt(abs(tstat), reg$df.residual, lower.tail = FALSE)
}

# wrap text
wrapper <- function(x, ...) paste(strwrap(x, ...), collapse = "\n")
```

```{r call packages}
library(readr)
library(readxl)
library(tidyverse)
library(lubridate)
library(ggpubr)
library(kableExtra)
library(broom)
library(MASS)
library(cutpointr)
library(ggstatsplot)
library(effects)
library(car)
# library(multcomp)
library(emmeans)
library(compute.es)
```

```{r} 
# COLOR BLIND PALETTE WITH BLACK
cbbPalette <- c("#000000", "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7")
cbbPalette2 <- c("#D55E00", "#E69F00", "#56B4E9", "#0072B2", "#CC79A7", "#009E73", "#F0E442")
```

# set seed for random process

```{r}
set.seed(1)
```

```{r import files}
dados_raw <- read_csv("dados_raw.csv")
```

# DATA PREPARATION

```{r create new variables}
# estimate cortical folding variables
dados_raw <- dados_raw %>%
  mutate(
    # create new variables
    logAvgThickness = log10(AvgThickness),
    logTotalArea = log10(TotalArea),
    logExposedArea = log10(ExposedArea),
    localGI = TotalArea / ExposedArea,
    k = sqrt(AvgThickness) * TotalArea / (ExposedArea ^ 1.25),
    K = 1 / 4 * log10(AvgThickness ^ 2)  + log10(TotalArea) - 5 / 4 * log10(ExposedArea),
    S = 3 / 2 * log10(TotalArea) + 3 / 4 * log10(ExposedArea) - 9 /  4 * log10(AvgThickness ^
                                                                                 2) ,
    I = log10(TotalArea) + log10(ExposedArea) + log10(AvgThickness ^ 2),
    c = as.double(ifelse(
      ROI == "hemisphere", NA, 4 * pi / GaussianCurvature
    )),
    TotalArea_corrected = ifelse(ROI == "hemisphere", TotalArea, TotalArea * c),
    ExposedArea_corrected = ifelse(ROI == "hemisphere", ExposedArea, ExposedArea * c),
    logTotalArea_corrected = log10(TotalArea_corrected),
    logExposedArea_corrected = log10(ExposedArea_corrected),
    localGI_corrected = ifelse(
      ROI == "hemisphere",
      TotalArea / ExposedArea,
      TotalArea_corrected / ExposedArea_corrected
    ),
    k_corrected = ifelse(
      ROI == "hemisphere",
      sqrt(AvgThickness) * log10(TotalArea) / (log10(ExposedArea) ^ 1.25),
      sqrt(AvgThickness) * log10(TotalArea_corrected) / (log10(ExposedArea_corrected ^
                                                                 1.25))
    ),
    K_corrected =  ifelse(
      ROI == "hemisphere",
      1 / 4 * log10(AvgThickness ^ 2) + log10(TotalArea) - 5 / 4 * log10(ExposedArea),
      1 / 4 * log10(AvgThickness ^ 2) + log10(TotalArea_corrected) - 5 / 4 * log10(ExposedArea_corrected)
    ),
    I_corrected = ifelse(
      ROI == "hemisphere",
      log10(TotalArea) + log10(ExposedArea) + log10(AvgThickness ^ 2) ,
      log10(TotalArea_corrected) + log10(ExposedArea_corrected) + log10(AvgThickness ^ 2)
    ),
    S_corrected = ifelse(
      ROI == "hemisphere",
      3 / 2 * log10(TotalArea) + 3 / 4 * log10(ExposedArea) - 9 /  4 * log10(AvgThickness ^ 2) ,
      3 / 2 * log10(TotalArea_corrected) + 3 / 4 * log10(ExposedArea_corrected) - 9 /  4 * log10(AvgThickness ^ 2)
    ),
    Knorm = K_corrected / sqrt(1 + (1 / 4) ^ 2 + (5 / 4) ^ 2),
    Snorm = S_corrected / sqrt((3 / 2) ^ 2 + (3 / 4) ^ 2 + (9 / 4) ^ 2),
    Inorm = I_corrected / sqrt(1 ^ 2 + 1 ^ 2 + 1 ^ 1)
  )

# create age intervals
dados_raw$Age_interval <- cut(dados_raw$Age,
                                       breaks = c(0, 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90, 95, 100),
                                       right = FALSE,
                                       include.lowest = TRUE)

dados_raw$Age_interval10 <- cut(dados_raw$Age,
                                         breaks = c(0, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100),
                                         right = FALSE,
                                         include.lowest = TRUE)
```

```{r data cleanup}
dados_all <- dados_raw %>% filter(
    Diagnostic == "CONTROLE" |
      Diagnostic == "CCL" |
      Diagnostic == "ALZ", !is.na(logAvgThickness), ExposedArea != 0 | !is.na(localGI), !is.infinite(logExposedArea)) %>% 
  droplevels()

dados <- dados_all
```

```{r}
# rename diagnostics
dados$Diagnostic[dados$Diagnostic == "CONTROLE"] <- "CTL"
dados$Diagnostic[dados$Diagnostic == "ALZ"] <- "AD"
dados$Diagnostic[dados$Diagnostic == "CCL"] <- "MCI"
dados$Diagnostic <- factor(dados$Diagnostic, levels = c("AD", "MCI","CTL"))

# filter data
dados <- dados %>%
  filter(machine == "Philips-Achieva", # include only subjects acquired at Philips Achieva 3T
                          ESC == 8 | ESC > 8, # include only subjects with 8 years of scholarship or more
                          Session == 1) %>% # use only data from Session 1
  droplevels() # delete factor levels
```

Visual QC exclusion:
```{r}
VisualQC <- read_excel("Verificacao qualidade segmentacao FS Zika e CCD.xlsx", 
    sheet = "AD - IDOR ses 1 long", col_types = c("text", 
        "text", "skip", "skip", "numeric", 
        "skip", "skip", "skip", "skip", "text", 
        "text")) %>%
  dplyr::select(-c(session)) %>%
  mutate(Session = 1)

dados <- full_join(dados, VisualQC) %>%
  filter(Classification == 1 | Classification == 2)
```

# Deaging

```{r deaging}
# define age for deaging
Age.cor = 25

## Avg thickness ----
decay_AvgThickness <-
  filter(
    dados,
    Diagnostic == "CTL",!is.na(TotalArea),!is.nan(TotalArea),!is.infinite(TotalArea)
  ) %>%
  droplevels() %>%
  group_by(ROI) %>%
  do(fit_decay_AvgThickness = tidy(rlm(AvgThickness ~ Age, data = .), conf.int =
                                     TRUE)) %>%
  unnest(cols = c(fit_decay_AvgThickness)) %>%
  filter(term == "Age") %>%
  mutate(c_AvgThickness = estimate,
         std_error_c_AvgThickness = std.error) %>%
  dplyr::select(c(ROI, c_AvgThickness, std_error_c_AvgThickness))

## TotalArea ----
decay_TotalArea <-
  filter(
    dados,
    Diagnostic == "CTL",
    !is.na(TotalArea),
    !is.nan(TotalArea),
    !is.infinite(TotalArea)
  ) %>%
  droplevels() %>%
  group_by(ROI) %>%
  do(fit_decay_TotalArea = tidy(rlm(TotalArea ~ Age, data = .), conf.int =
                                  TRUE)) %>%
  unnest(cols = c(fit_decay_TotalArea)) %>%
  filter(term == "Age") %>%
  mutate(c_TotalArea = estimate,
         std_error_c_TotalArea = std.error) %>%
  dplyr::select(c(ROI, c_TotalArea, std_error_c_TotalArea))

## ExposedArea ----
decay_ExposedArea <-
  filter(
    dados,
    Diagnostic == "CTL",
    !is.na(ExposedArea),
    !is.nan(ExposedArea),
    !is.infinite(ExposedArea)
  ) %>%
  droplevels() %>%
  group_by(ROI) %>%
  do(fit_decay_ExposedArea = tidy(rlm(ExposedArea ~ Age, data = .), conf.int = TRUE)) %>%
  unnest(cols = c(fit_decay_ExposedArea)) %>%
  filter(term == "Age") %>%
  mutate(c_ExposedArea = estimate,
         std_error_c_ExposedArea = std.error) %>%
  dplyr::select(c(ROI, c_ExposedArea, std_error_c_ExposedArea))

## join
dados <- full_join(dados, decay_AvgThickness) %>%
  full_join(decay_TotalArea) %>%
  full_join(decay_ExposedArea) %>%
  mutate(
    AvgThickness_age_decay = AvgThickness - c_AvgThickness * (Age - Age.cor),
    logAvgThickness_age_decay = log10(AvgThickness_age_decay),
    TotalArea_age_decay = TotalArea - c_TotalArea * (Age - Age.cor),
    logTotalArea_age_decay = log10(TotalArea_age_decay),
    ExposedArea_age_decay = ExposedArea - c_ExposedArea * (Age - Age.cor),
    logExposedArea_age_decay = log10(ExposedArea_age_decay),
    localGI_age_decay = TotalArea_age_decay / ExposedArea_age_decay,
    K_age_decay = log10(TotalArea_age_decay) + 1/4*log10(AvgThickness_age_decay^2) - 5/4*log10(ExposedArea_age_decay),
    I_age_decay = log10(TotalArea_age_decay) + log10(ExposedArea_age_decay) + log10(AvgThickness_age_decay^2),
    S_age_decay = 3/2*log10(TotalArea_age_decay) + 3/4*log10(ExposedArea_age_decay) - 9/4*log10(AvgThickness_age_decay^2))

dados$logAvgThickness <- as.double(dados$logAvgThickness)
dados$logExposedArea <- as.double(dados$logExposedArea)
dados$logTotalArea   <- as.double(dados$logTotalArea)

```

```{r}
dados_v1 <- filter(dados, ROI == "F" | ROI == "T" | ROI == "O" | ROI == "P" | ROI == "hemisphere") %>%
  droplevels()

# lobe data
dados_lobos_v1 <- unique(filter(dados, ROI == "F" | ROI == "T" | ROI == "O" | ROI == "P",  !is.na(K_age_decay), SUBJ != "SUBJ211", SUBJ != "SUBJ223")) %>%
  droplevels()

# hemisphere data
dados_hemi_v1 <- unique(filter(dados, ROI == "hemisphere", !is.na(K_age_decay)))
```

```{r include=FALSE}
write.csv(dados_v1, "dados_v1.csv")
```

# RESULTS

### Aging and pathological morphology alterations

```{r, echo=FALSE, message=FALSE, warning=FALSE}
dados_hemi_v1 %>%
  group_by(Diagnostic, Age_interval10) %>%
  summarise(
    N = n_distinct(SUBJ),
    age = paste(signif(mean(Age), 2), "±", signif(sd(Age), 2)),
    age_range = paste(signif(min(Age), 2), "; ", signif(max(Age), 2)),
    ESC = paste(signif(mean(ESC), 2), "±", signif(sd(ESC), 2))
  ) %>%
  kable(digits = 2) %>%
  kable_styling()
```

```{python}
import numpy as np
def perm_indices(ts, wl¼4, lag¼1):
  m ¼ len(ts)(wl1)lag
  indcs ¼ np.zeros(m, dtype¼int)
  for i in xrange(1,wl):
    st ¼ ts[(i1)lag : mþ ðði1ÞlagÞ]
    for j in xrange(i,wl):
      indcs þ ¼st4ts½jlag : mþjlag]
    indcs¼ wli
return indcs þ 1
```



```{r}
mean_K_I_S_agegroups <-
  dados_hemi_v1_agegroups %>% group_by(Diagnostic, Age_interval10) %>% summarise(
    # mean.T = mean(logAvgThickness, na.rm = TRUE),
    # SD_T = sd(logAvgThickness, na.rm = TRUE),
    mean.K = mean(Knorm, na.rm = TRUE),
    SD_K = sd(Knorm, na.rm = TRUE),
    mean.I = mean(Inorm, na.rm = TRUE),
    SD_I = sd(Inorm, na.rm = TRUE),
    mean.S = mean(Snorm, na.rm = TRUE),
    SD_S = sd(Snorm, na.rm = TRUE),
    N_SUBJ = n_distinct(SUBJ)
  )

write.csv(mean_K_I_S_agegroups, "datafig3.csv")

```

```{r}
fig3b <- ggplot(mean_K_I_S_agegroups, aes(x = mean.K, y = mean.S, color = Diagnostic, shape = Age_interval10))+
    geom_point() +
    geom_line(aes(group = Diagnostic)) +
    #geom_text(aes(label=Age.group), nudge_y = 0.1, size =3)+
    theme_pubr() + 
  # guides(color = "none") + 
    labs(shape = "Age", x = "K (normalized)", y = "S (normalized)") +
    # theme(axis.title = element_text(size = 11),
    #       axis.text = element_text(size = 10), text = element_text(size = 10)) +
  scale_fill_manual(values=cbbPalette2) +
  scale_colour_manual(values=cbbPalette2) +
  theme(legend.position="bottom", legend.box="vertical", legend.margin=margin())

fig3b

```

```{r}
fig3b_Alt <- ggplot(mean_K_I_S_agegroups, aes(x = mean.K, y = mean.S, color = Diagnostic, shape = Age_interval10))+
    geom_point() +
    geom_line(aes(group = Diagnostic)) +
  geom_errorbar(aes(ymin = mean.S - SD_S, ymax = mean.S + SD_S))  +
  geom_errorbarh(aes(xmin = mean.K - SD_K, xmax = mean.K + SD_K))  +
  geom_point(data = dados_hemi_v1_agegroups, aes(x = Knorm, y = Snorm, color = Diagnostic, shape = Age_interval10), alpha = 0.2) +
    #geom_text(aes(label=Age.group), nudge_y = 0.1, size =3)+
    theme_pubr() + 
  # guides(color = "none") + 
    labs(shape = "Age", x = "K (normalized)", y = "S (normalized)") +
    # theme(axis.title = element_text(size = 11),
    #       axis.text = element_text(size = 10), text = element_text(size = 10)) +
  scale_fill_manual(values=cbbPalette2) +
  scale_colour_manual(values=cbbPalette2) +
  theme(legend.position="bottom", legend.box="vertical", legend.margin=margin())

fig3b_Alt
```

```{r}
fig3d <- ggplot(mean_K_I_S_agegroups, aes(x = mean.K, y = mean.I, color = Diagnostic, shape = Age_interval10))+
    geom_point() +
    geom_line(aes(group = Diagnostic)) +
    #geom_text(aes(label=Age.group), nudge_y = 0.1, size =3)+
    theme_pubr() +
  # guides(color = "none") + 
    labs(shape = "Age", x = "K (normalized)", y = "I (normalized)")  +
    # theme(axis.title = element_text(size = 11),
    #       axis.text = element_text(size = 10), text = element_text(size = 10)) +
  scale_fill_manual(values=cbbPalette2) +
  scale_colour_manual(values=cbbPalette2) +
  theme(legend.position="bottom" , legend.box="vertical", legend.margin=margin())

fig3d

```

```{r}
fig3d_Alt <- ggplot(mean_K_I_S_agegroups, aes(x = mean.K, y = mean.I, color = Diagnostic, shape = Age_interval10))+
    geom_point() +
    geom_line(aes(group = Diagnostic)) +
    geom_errorbar(aes(ymin = mean.I - SD_I, ymax = mean.I + SD_I))  +
  geom_errorbarh(aes(xmin = mean.K - SD_K, xmax = mean.K + SD_K))  +
  geom_point(data = dados_hemi_v1_agegroups, aes(x = Knorm, y = Inorm, color = Diagnostic, shape = Age_interval10), alpha = 0.2) +
    #geom_text(aes(label=Age.group), nudge_y = 0.1, size =3)+
    theme_pubr() + 
  # guides(color = "none") + 
    labs(shape = "Age", x = "K (normalized)", y = "I (normalized)") +
    # theme(axis.title = element_text(size = 11),
    #       axis.text = element_text(size = 10), text = element_text(size = 10)) +
  scale_fill_manual(values=cbbPalette2) +
  scale_colour_manual(values=cbbPalette2) +
  theme(legend.position="bottom", legend.box="vertical", legend.margin=margin())
fig3d_Alt
```

```{r}
fig3s <- ggarrange(fig3b, fig3d, labels = c("A", "B"), nrow=2, font.label = list(size = 11), common.legend = TRUE, legend = "bottom")

fig3s
```


```{r}
fig3s_Alt_allgroups <- ggarrange(fig3b_Alt, fig3d_Alt, labels = c("A", "B"),ncol = 2, nrow=1, font.label = list(size = 11), common.legend = TRUE, legend = "bottom")

fig3s_Alt_allgroups

# ggsave("fig3s_Alt_allgroups.png",fig3s_Alt_allgroups, width = 18, height = 9, units = "cm", device = "png")
```

### FIGURE 3 with age intervals - age corrected

```{r}
mean_K_I_S_agegroups <-
  filter(dados_hemi_v1_agegroups) %>% group_by(Diagnostic, Age_interval10) %>% summarise(
    mean.T = mean(logAvgThickness, na.rm = TRUE),
    SD_T = sd(logAvgThickness, na.rm = TRUE),
    mean.K = mean(K_age_decay/ sqrt(1 + (1 / 4) ^ 2 + (5 / 4) ^ 2), na.rm = TRUE),
    SD_K = sd(K_age_decay/ sqrt(1 + (1 / 4) ^ 2 + (5 / 4) ^ 2), na.rm = TRUE),
    mean.I = mean(I_age_decay/ sqrt(1 ^ 2 + 1 ^ 2 + 1 ^ 1), na.rm = TRUE),
    SD_I = sd(I_age_decay/ sqrt(1 ^ 2 + 1 ^ 2 + 1 ^ 1), na.rm = TRUE),
    mean.S = mean(S_age_decay/ sqrt((3 / 2) ^ 2 + (3 / 4) ^ 2 + (9 / 4) ^ 2), na.rm = TRUE),
    SD_S = sd(S_age_decay/ sqrt((3 / 2) ^ 2 + (3 / 4) ^ 2 + (9 / 4) ^ 2), na.rm = TRUE),
    N_SUBJ = n_distinct(SUBJ)
  )
```

```{r}
fig3b <- ggplot(mean_K_I_S_agegroups, aes(x = mean.K, y = mean.S, color = Diagnostic, shape = Age_interval10))+
    geom_point() +
    geom_line(aes(group = Diagnostic)) +
    #geom_text(aes(label=Age.group), nudge_y = 0.1, size =3)+
    theme_pubr() + 
  # guides(color = "none") + 
    labs(shape = "Age", x = "K (normalized)", y = "S (normalized)") +
    # theme(axis.title = element_text(size = 11),
    #       axis.text = element_text(size = 10), text = element_text(size = 10)) +
  scale_fill_manual(values=cbbPalette2) +
  scale_colour_manual(values=cbbPalette2) +
  theme(legend.position="bottom", legend.box="vertical", legend.margin=margin())

fig3b

```

```{r}
fig3b_Alt <- ggplot(mean_K_I_S_agegroups, aes(x = mean.K, y = mean.S, color = Diagnostic, shape = Age_interval10))+
    geom_point() +
    geom_line(aes(group = Diagnostic)) +
  geom_errorbar(aes(ymin = mean.S - SD_S, ymax = mean.S + SD_S))  +
  geom_errorbarh(aes(xmin = mean.K - SD_K, xmax = mean.K + SD_K))  +
  geom_point(data = dados_hemi_v1_agegroups, aes(x = Knorm, y = Snorm, color = Diagnostic, shape = Age_interval10), alpha = 0.2) +
    #geom_text(aes(label=Age.group), nudge_y = 0.1, size =3)+
    theme_pubr() + 
  # guides(color = "none") + 
    labs(shape = "Age", x = "K (normalized)", y = "S (normalized)") +
    # theme(axis.title = element_text(size = 11),
    #       axis.text = element_text(size = 10), text = element_text(size = 10)) +
  scale_fill_manual(values=cbbPalette2) +
  scale_colour_manual(values=cbbPalette2) +
  theme(legend.position="bottom", legend.box="vertical", legend.margin=margin())

fig3b_Alt
```

```{r}
fig3d <- ggplot(mean_K_I_S_agegroups, aes(x = mean.K, y = mean.I, color = Diagnostic, shape = Age_interval10))+
    geom_point() +
    geom_line(aes(group = Diagnostic)) +
    #geom_text(aes(label=Age.group), nudge_y = 0.1, size =3)+
    theme_pubr() +
  # guides(color = "none") + 
    labs(shape = "Age", x = "K (normalized)", y = "I (normalized)")  +
    # theme(axis.title = element_text(size = 11),
    #       axis.text = element_text(size = 10), text = element_text(size = 10)) +
  scale_fill_manual(values=cbbPalette2) +
  scale_colour_manual(values=cbbPalette2) +
  theme(legend.position="bottom" , legend.box="vertical", legend.margin=margin())

fig3d

```

```{r}
fig3d_Alt <- ggplot(mean_K_I_S_agegroups, aes(x = mean.K, y = mean.I, color = Diagnostic, shape = Age_interval10))+
    geom_point() +
    geom_line(aes(group = Diagnostic)) +
    geom_errorbar(aes(ymin = mean.I - SD_I, ymax = mean.I + SD_I))  +
  geom_errorbarh(aes(xmin = mean.K - SD_K, xmax = mean.K + SD_K))  +
  geom_point(data = dados_hemi_v1_agegroups, aes(x = Knorm, y = Inorm, color = Diagnostic, shape = Age_interval10), alpha = 0.2) +
    #geom_text(aes(label=Age.group), nudge_y = 0.1, size =3)+
    theme_pubr() + 
  # guides(color = "none") + 
    labs(shape = "Age", x = "K (normalized)", y = "I (normalized)") +
    # theme(axis.title = element_text(size = 11),
    #       axis.text = element_text(size = 10), text = element_text(size = 10)) +
  scale_fill_manual(values=cbbPalette2) +
  scale_colour_manual(values=cbbPalette2) +
  theme(legend.position="bottom", legend.box="vertical", legend.margin=margin())
fig3d_Alt
```

```{r}
fig3s <- ggarrange(fig3b, fig3d, labels = c("A", "B"), nrow=2, font.label = list(size = 11), common.legend = TRUE, legend = "bottom")

fig3s
```

```{r}
fig3s_Alt <- ggarrange(fig3b_Alt, fig3d_Alt, labels = c("A", "B"),ncol = 2, nrow=1, font.label = list(size = 11), common.legend = TRUE, legend = "bottom")

fig3s_Alt
```

```{r eval=FALSE, include=FALSE}

ggplot(dados_hemi_v1, aes(x = Diagnostic, y = S, color = Diagnostic, fill = Diagnostic, alpha = 0.4)) +
  geom_boxplot() +
 stat_compare_means(method = "anova") +
  theme_pubr() +
  scale_fill_manual(values=cbbPalette2) +
  scale_colour_manual(values=cbbPalette2)

aov_diag_S <- aov(S ~ Diagnostic, data = dados_hemi_v1)
summary(aov_diag_S)
aov_diag_S_diag_TK <- TukeyHSD(aov_diag_S)
#aov_diag_S_diag_TK

aov_diag_S_diag_TK_t <- mutate(as.data.frame(aov_diag_S_diag_TK$Diagnostic), Contrast = c("MCI-AD", "CTL-AD", "CTL-MCI") , morphological_parameter = "S", Age_correction = "no", ROI = "hemisphere")

ggplot(dados_hemi_v1, aes(x = Diagnostic, y = S_age_decay, color = Diagnostic, fill = Diagnostic, alpha = 0.4)) +
  geom_boxplot() +
 stat_compare_means(method = "anova") +
  theme_pubr() +
  scale_fill_manual(values=cbbPalette2) +
  scale_colour_manual(values=cbbPalette2)

aov_diag_S_age_decay <- aov(S_age_decay ~ Diagnostic, data = dados_hemi_v1)
summary(aov_diag_S_age_decay)
aov_diag_S_age_decay_diag_TK <- TukeyHSD(aov_diag_S_age_decay)
#aov_diag_S_age_decay_diag_TK

aov_diag_S_age_decay_diag_TK_t <- mutate(as.data.frame(aov_diag_S_age_decay_diag_TK$Diagnostic), Contrast = c("MCI-AD", "CTL-AD", "CTL-MCI") , morphological_parameter = "S", Age_correction = "yes", ROI = "hemisphere")

```

